spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
    path: /h2-console
    profiles:
      active: local
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    open-in-view: false
  sql:
    init:
      data-locations: classpath:data.sql
      schema-locations: classpath:table.sql
      mode: always